// SC2 原版图标本地路径映射表。
// 图标已下载到 web/public/icons/sc2/{buildings,upgrades}/
// 下载脚本：scripts/download_sc2_icons.py
// 来源：Liquipedia wiki（MIT/CC 授权，教育用途）
//
// fallback：图标加载失败时组件显示灰底缩写文字。

// 升级 / 科技图标（key = UpgradeId.name 大写）
export const UPGRADE_ICONS: Record<string, string> = {
  // ---- 神族攻防护 ----
  PROTOSSGROUNDWEAPONSLEVEL1: '/icons/sc2/upgrades/PROTOSSGROUNDWEAPONSLEVEL1.gif',
  PROTOSSGROUNDWEAPONSLEVEL2: '/icons/sc2/upgrades/PROTOSSGROUNDWEAPONSLEVEL2.gif',
  PROTOSSGROUNDWEAPONSLEVEL3: '/icons/sc2/upgrades/PROTOSSGROUNDWEAPONSLEVEL3.gif',
  PROTOSSGROUNDARMORSLEVEL1:  '/icons/sc2/upgrades/PROTOSSGROUNDARMORSLEVEL1.gif',
  PROTOSSGROUNDARMORSLEVEL2:  '/icons/sc2/upgrades/PROTOSSGROUNDARMORSLEVEL2.gif',
  PROTOSSGROUNDARMORSLEVEL3:  '/icons/sc2/upgrades/PROTOSSGROUNDARMORSLEVEL3.gif',
  PROTOSSSHIELDSLEVEL1: '/icons/sc2/upgrades/PROTOSSSHIELDSLEVEL1.gif',
  PROTOSSSHIELDSLEVEL2: '/icons/sc2/upgrades/PROTOSSSHIELDSLEVEL2.gif',
  PROTOSSSHIELDSLEVEL3: '/icons/sc2/upgrades/PROTOSSSHIELDSLEVEL3.gif',
  PROTOSSAIRWEAPONSLEVEL1: '/icons/sc2/upgrades/PROTOSSAIRWEAPONSLEVEL1.gif',
  PROTOSSAIRWEAPONSLEVEL2: '/icons/sc2/upgrades/PROTOSSAIRWEAPONSLEVEL2.gif',
  PROTOSSAIRWEAPONSLEVEL3: '/icons/sc2/upgrades/PROTOSSAIRWEAPONSLEVEL3.gif',
  PROTOSSAIRARMORSLEVEL1:  '/icons/sc2/upgrades/PROTOSSAIRARMORSLEVEL1.gif',
  PROTOSSAIRARMORSLEVEL2:  '/icons/sc2/upgrades/PROTOSSAIRARMORSLEVEL2.gif',
  PROTOSSAIRARMORSLEVEL3:  '/icons/sc2/upgrades/PROTOSSAIRARMORSLEVEL3.gif',
  // ---- 神族兵种 ----
  WARPGATERESEARCH:          '/icons/sc2/upgrades/WARPGATERESEARCH.gif',
  CHARGE:                    '/icons/sc2/upgrades/CHARGE.png',
  BLINKTECH:                 '/icons/sc2/upgrades/BLINKTECH.png',
  ADEPTPIERCINGATTACK:       '/icons/sc2/upgrades/ADEPTPIERCINGATTACK.jpg',
  PSISTORMTECH:              '/icons/sc2/upgrades/PSISTORMTECH.png',
  HALLUCINATION:             '/icons/sc2/upgrades/HALLUCINATION.png',
  OBSERVERGRAVITICBOOSTER:   '/icons/sc2/upgrades/OBSERVERGRAVITICBOOSTER.gif',
  GRAVITICDRIVE:             '/icons/sc2/upgrades/GRAVITICDRIVE.gif',
  EXTENDEDTHERMALLANCE:      '/icons/sc2/upgrades/EXTENDEDTHERMALLANCE.gif',
  PHOENIXRANGEUPGRADE:       '/icons/sc2/upgrades/PHOENIXRANGEUPGRADE.png',
  CARRIERLAUNCHSPEEDUPGRADE: '/icons/sc2/upgrades/CARRIERLAUNCHSPEEDUPGRADE.gif',
  DARKTEMPLARALASADIR:       '/icons/sc2/upgrades/DARKTEMPLARALASADIR.png',
  // ---- 虫族攻防 ----
  ZERGGROUNDARMORSLEVEL1: '/icons/sc2/upgrades/ZERGGROUNDARMORSLEVEL1.gif',
  ZERGGROUNDARMORSLEVEL2: '/icons/sc2/upgrades/ZERGGROUNDARMORSLEVEL2.gif',
  ZERGGROUNDARMORSLEVEL3: '/icons/sc2/upgrades/ZERGGROUNDARMORSLEVEL3.gif',
  ZERGMELEEWEAPONSLEVEL1: '/icons/sc2/upgrades/ZERGMELEEWEAPONSLEVEL1.gif',
  ZERGMELEEWEAPONSLEVEL2: '/icons/sc2/upgrades/ZERGMELEEWEAPONSLEVEL2.gif',
  ZERGMELEEWEAPONSLEVEL3: '/icons/sc2/upgrades/ZERGMELEEWEAPONSLEVEL3.gif',
  ZERGMISSILEWEAPONSLEVEL1: '/icons/sc2/upgrades/ZERGMISSILEWEAPONSLEVEL1.gif',
  ZERGMISSILEWEAPONSLEVEL2: '/icons/sc2/upgrades/ZERGMISSILEWEAPONSLEVEL2.gif',
  ZERGMISSILEWEAPONSLEVEL3: '/icons/sc2/upgrades/ZERGMISSILEWEAPONSLEVEL3.gif',
  ZERGFLYERATTACKLEVEL1: '/icons/sc2/upgrades/ZERGFLYERATTACKLEVEL1.gif',
  ZERGFLYERATTACKLEVEL2: '/icons/sc2/upgrades/ZERGFLYERATTACKLEVEL2.gif',
  ZERGFLYERATTACKLEVEL3: '/icons/sc2/upgrades/ZERGFLYERATTACKLEVEL3.gif',
  ZERGFLYERARMORSLEVEL1: '/icons/sc2/upgrades/ZERGFLYERARMORSLEVEL1.gif',
  ZERGFLYERARMORSLEVEL2: '/icons/sc2/upgrades/ZERGFLYERARMORSLEVEL2.gif',
  ZERGFLYERARMORSLEVEL3: '/icons/sc2/upgrades/ZERGFLYERARMORSLEVEL3.gif',
  // ---- 虫族兵种 ----
  ZERGLINGATTACKSPEED:     '/icons/sc2/upgrades/ZERGLINGATTACKSPEED.gif',
  ZERGLINGMOVEMENTSPEED:   '/icons/sc2/upgrades/ZERGLINGMOVEMENTSPEED.gif',
  BANELINGMOVEMENTSPEED:   '/icons/sc2/upgrades/BANELINGMOVEMENTSPEED.gif',
  TUNNELINGCLAWS:          '/icons/sc2/upgrades/TUNNELINGCLAWS.gif',
  GLIALRECONSTITUTION:     '/icons/sc2/upgrades/GLIALRECONSTITUTION.gif',
  CENTRIFICALHOOKS:        '/icons/sc2/upgrades/CENTRIFICALHOOKS.gif',
  EVOLVEGROOVEDSPINES:     '/icons/sc2/upgrades/EVOLVEGROOVEDSPINES.png',
  EVOLVEMUSCULARAUGMENTS:  '/icons/sc2/upgrades/EVOLVEMUSCULARAUGMENTS.png',
  LURKERRANGE:             '/icons/sc2/upgrades/LURKERRANGE.png',
  CHITINOUSPLATING:        '/icons/sc2/upgrades/CHITINOUSPLATING.gif',
  ANABOLICSYNTHESIS:       '/icons/sc2/upgrades/ANABOLICSYNTHESIS.gif',
  OVERLORDSPEED:           '/icons/sc2/upgrades/OVERLORDSPEED.gif',
  BURROW:                  '/icons/sc2/upgrades/BURROW.gif',
  NEURALPARASITE:          '/icons/sc2/upgrades/NEURALPARASITE.png',
  // ---- 人族攻防 ----
  TERRANINFANTRYWEAPONSLEVEL1: '/icons/sc2/upgrades/TERRANINFANTRYWEAPONSLEVEL1.gif',
  TERRANINFANTRYWEAPONSLEVEL2: '/icons/sc2/upgrades/TERRANINFANTRYWEAPONSLEVEL2.gif',
  TERRANINFANTRYWEAPONSLEVEL3: '/icons/sc2/upgrades/TERRANINFANTRYWEAPONSLEVEL3.gif',
  TERRANINFANTRYARMORSLEVEL1:  '/icons/sc2/upgrades/TERRANINFANTRYARMORSLEVEL1.gif',
  TERRANINFANTRYARMORSLEVEL2:  '/icons/sc2/upgrades/TERRANINFANTRYARMORSLEVEL2.gif',
  TERRANINFANTRYARMORSLEVEL3:  '/icons/sc2/upgrades/TERRANINFANTRYARMORSLEVEL3.gif',
  TERRANVEHICLEWEAPONSLEVEL1:  '/icons/sc2/upgrades/TERRANVEHICLEWEAPONSLEVEL1.gif',
  TERRANVEHICLEWEAPONSLEVEL2:  '/icons/sc2/upgrades/TERRANVEHICLEWEAPONSLEVEL2.gif',
  TERRANVEHICLEWEAPONSLEVEL3:  '/icons/sc2/upgrades/TERRANVEHICLEWEAPONSLEVEL3.gif',
  TERRANVEHICLEANDSHIPARMORSLEVEL1: '/icons/sc2/upgrades/TERRANVEHICLEANDSHIPARMORSLEVEL1.gif',
  TERRANVEHICLEANDSHIPARMORSLEVEL2: '/icons/sc2/upgrades/TERRANVEHICLEANDSHIPARMORSLEVEL2.gif',
  TERRANVEHICLEANDSHIPARMORSLEVEL3: '/icons/sc2/upgrades/TERRANVEHICLEANDSHIPARMORSLEVEL3.gif',
  TERRANSHIPWEAPONSLEVEL1:     '/icons/sc2/upgrades/TERRANSHIPWEAPONSLEVEL1.gif',
  TERRANSHIPWEAPONSLEVEL2:     '/icons/sc2/upgrades/TERRANSHIPWEAPONSLEVEL2.gif',
  TERRANSHIPWEAPONSLEVEL3:     '/icons/sc2/upgrades/TERRANSHIPWEAPONSLEVEL3.gif',
  // ---- 人族兵种 ----
  STIMPACK:                    '/icons/sc2/upgrades/STIMPACK.png',
  COMBATSHIELD:                '/icons/sc2/upgrades/COMBATSHIELD.png',
  PUNISHERGRENADES:            '/icons/sc2/upgrades/PUNISHERGRENADES.png',
  SIEGETECH:                   '/icons/sc2/upgrades/SIEGETECH.gif',
  HIGHCAPACITYBARRELS:         '/icons/sc2/upgrades/HIGHCAPACITYBARRELS.jpg',
  DRILLCLAWS:                  '/icons/sc2/upgrades/DRILLCLAWS.png',
  BATTLECRUISERENABLESPECIALIZATIONS: '/icons/sc2/upgrades/BATTLECRUISERENABLESPECIALIZATIONS.gif',
  MEDIVACINCREASESPEEDBOOST:   '/icons/sc2/upgrades/MEDIVACINCREASESPEEDBOOST.gif',
  NEOSTEELFRAME:               '/icons/sc2/upgrades/NEOSTEELFRAME.gif',
  HISECAUTOTRACKING:           '/icons/sc2/upgrades/HISECAUTOTRACKING.gif',
  BANSHEESPEED:                '/icons/sc2/upgrades/BANSHEESPEED.jpg',
  BANSHEECLOAK:                '/icons/sc2/upgrades/BANSHEECLOAK.png',
  GHOSTCLOAK:                  '/icons/sc2/upgrades/GHOSTCLOAK.png',
  TACNUKESILO:                 '/icons/sc2/upgrades/TACNUKESILO.png',
  LIBERATORAGRANGEUPGRADE:     '/icons/sc2/upgrades/LIBERATORAGRANGEUPGRADE.jpg',
}

// 兵种图标（key = UnitTypeId.name 大写）
// 下载来源：Liquipedia wiki（imageinfo API 探测 2026-06-02）。
// 无图标的兵种（凤凰/使徒/哨兵/白球/巨像/OB/航母/风暴/蜂巢/维京战机）前端显示中文 fallback。
export const UNIT_ICONS: Record<string, string> = {
  // ---- 神族 ----
  PROBE:         '/icons/sc2/units/PROBE.jpg',
  ZEALOT:        '/icons/sc2/units/ZEALOT.jpg',
  STALKER:       '/icons/sc2/units/STALKER.png',
  IMMORTAL:      '/icons/sc2/units/IMMORTAL.png',
  HIGHTEMPLAR:   '/icons/sc2/units/HIGHTEMPLAR.png',
  DARKTEMPLAR:   '/icons/sc2/units/DARKTEMPLAR.png',
  WARPPRISM:     '/icons/sc2/units/WARPPRISM.png',
  VOIDRAY:       '/icons/sc2/units/VOIDRAY.png',
  MOTHERSHIP:    '/icons/sc2/units/MOTHERSHIP.png',
  DISRUPTOR:     '/icons/sc2/units/DISRUPTOR.jpg',
  // ---- 虫族 ----
  DRONE:         '/icons/sc2/units/DRONE.jpg',
  QUEEN:         '/icons/sc2/units/QUEEN.jpg',
  ZERGLING:      '/icons/sc2/units/ZERGLING.jpg',
  BANELING:      '/icons/sc2/units/BANELING.jpg',
  ROACH:         '/icons/sc2/units/ROACH.png',
  RAVAGER:       '/icons/sc2/units/RAVAGER.png',
  HYDRALISK:     '/icons/sc2/units/HYDRALISK.jpg',
  LURKERMP:      '/icons/sc2/units/LURKERMP.jpg',
  INFESTOR:      '/icons/sc2/units/INFESTOR.png',
  ULTRALISK:     '/icons/sc2/units/ULTRALISK.jpg',
  OVERSEER:      '/icons/sc2/units/OVERSEER.png',
  MUTALISK:      '/icons/sc2/units/MUTALISK.jpg',
  CORRUPTOR:     '/icons/sc2/units/CORRUPTOR.png',
  BROODLORD:     '/icons/sc2/units/BROODLORD.png',
  VIPER:         '/icons/sc2/units/VIPER.jpg',
  // ---- 人族 ----
  SCV:           '/icons/sc2/units/SCV.png',
  MARINE:        '/icons/sc2/units/MARINE.png',
  MARAUDER:      '/icons/sc2/units/MARAUDER.png',
  REAPER:        '/icons/sc2/units/REAPER.png',
  GHOST:         '/icons/sc2/units/GHOST.png',
  HELLION:       '/icons/sc2/units/HELLION.png',
  WIDOWMINE:     '/icons/sc2/units/WIDOWMINE.png',
  SIEGETANK:     '/icons/sc2/units/SIEGETANK.png',
  CYCLONE:       '/icons/sc2/units/CYCLONE.png',
  THOR:          '/icons/sc2/units/THOR.png',
  VIKINGFIGHTER: '/icons/sc2/units/VIKINGFIGHTER.png',
  MEDIVAC:       '/icons/sc2/units/MEDIVAC.png',
  LIBERATOR:     '/icons/sc2/units/LIBERATOR.png',
  RAVEN:         '/icons/sc2/units/RAVEN.png',
  BANSHEE:       '/icons/sc2/units/BANSHEE.png',
  BATTLECRUISER: '/icons/sc2/units/BATTLECRUISER.jpg',
}

// 产能建筑图标（key = UnitTypeId.name 大写）
export const BUILDING_ICONS: Record<string, string> = {
  // 神族
  NEXUS:             '/icons/sc2/buildings/NEXUS.jpg',
  GATEWAY:           '/icons/sc2/buildings/GATEWAY.jpg',
  WARPGATE:          '/icons/sc2/buildings/WARPGATE.jpg',
  STARGATE:          '/icons/sc2/buildings/STARGATE.jpg',
  ROBOTICSFACILITY:  '/icons/sc2/buildings/ROBOTICSFACILITY.jpg',
  // 虫族
  HATCHERY:          '/icons/sc2/buildings/HATCHERY.jpg',
  LAIR:              '/icons/sc2/buildings/LAIR.jpg',
  HIVE:              '/icons/sc2/buildings/HIVE.jpg',
  // 人族
  COMMANDCENTER:     '/icons/sc2/buildings/COMMANDCENTER.jpg',
  ORBITALCOMMAND:    '/icons/sc2/buildings/ORBITALCOMMAND.jpg',
  PLANETARYFORTRESS: '/icons/sc2/buildings/PLANETARYFORTRESS.jpg',
  BARRACKS:          '/icons/sc2/buildings/BARRACKS.jpg',
  FACTORY:           '/icons/sc2/buildings/FACTORY.jpg',
  STARPORT:          '/icons/sc2/buildings/STARPORT.jpg',
  // 关键科技建筑（科技行用：只体现有/没有 + 建成/建造中）
  // 神族
  CYBERNETICSCORE:   '/icons/sc2/buildings/CYBERNETICSCORE.jpg',
  FORGE:             '/icons/sc2/buildings/FORGE.jpg',
  TWILIGHTCOUNCIL:   '/icons/sc2/buildings/TWILIGHTCOUNCIL.jpg',
  ROBOTICSBAY:       '/icons/sc2/buildings/ROBOTICSBAY.jpg',
  FLEETBEACON:       '/icons/sc2/buildings/FLEETBEACON.jpg',
  TEMPLARARCHIVE:    '/icons/sc2/buildings/TEMPLARARCHIVE.jpg',
  DARKSHRINE:        '/icons/sc2/buildings/DARKSHRINE.jpg',
  // 虫族
  SPAWNINGPOOL:      '/icons/sc2/buildings/SPAWNINGPOOL.jpg',
  ROACHWARREN:       '/icons/sc2/buildings/ROACHWARREN.jpg',
  BANELINGNEST:      '/icons/sc2/buildings/BANELINGNEST.jpg',
  EVOLUTIONCHAMBER:  '/icons/sc2/buildings/EVOLUTIONCHAMBER.jpg',
  HYDRALISKDEN:      '/icons/sc2/buildings/HYDRALISKDEN.jpg',
  LURKERDENMP:       '/icons/sc2/buildings/LURKERDENMP.jpg',
  INFESTATIONPIT:    '/icons/sc2/buildings/INFESTATIONPIT.jpg',
  SPIRE:             '/icons/sc2/buildings/SPIRE.jpg',
  GREATERSPIRE:      '/icons/sc2/buildings/GREATERSPIRE.jpg',
  ULTRALISKCAVERN:   '/icons/sc2/buildings/ULTRALISKCAVERN.jpg',
  NYDUSNETWORK:      '/icons/sc2/buildings/NYDUSNETWORK.jpg',
  // 人族
  ENGINEERINGBAY:    '/icons/sc2/buildings/ENGINEERINGBAY.jpg',
  ARMORY:            '/icons/sc2/buildings/ARMORY.jpg',
  GHOSTACADEMY:      '/icons/sc2/buildings/GHOSTACADEMY.jpg',
  FUSIONCORE:        '/icons/sc2/buildings/FUSIONCORE.jpg',
}
